import * as fs from "fs";

const bookies = {
  "1xbet:bj": {
    bookie: "1xbet:bj",
    from: "1",
    to: "1",
    name: "1xbet -Benin",
    brand: "1xbet",
    img: "",
  },
  "1xbet:ci": {
    bookie: "1xbet:ci",
    from: "1",
    to: "1",
    name: "1xbet -Côte d'Ivoire",
    brand: "1xbet",
    img: "",
  },
  "1xbet:cm": {
    bookie: "1xbet:cm",
    from: "1",
    to: "1",
    name: "1xbet -Cameroon",
    brand: "1xbet",
    img: "",
  },
  "1xbet:gh": {
    bookie: "1xbet:gh",
    from: "1",
    to: "1",
    name: "1xbet -Ghana",
    brand: "1xbet",
    img: "",
  },
  "1xbet:ke": {
    bookie: "1xbet:ke",
    from: "1",
    to: "1",
    name: "1xbet -Kenya",
    brand: "1xbet",
    img: "",
  },
  "1xbet:mw": {
    bookie: "1xbet:mw",
    from: "1",
    to: "1",
    name: "1xbet -Malawi",
    brand: "1xbet",
    img: "",
  },
  "1xbet:ng": {
    bookie: "1xbet:ng",
    from: "1",
    to: "1",
    name: "1xbet -Nigeria",
    brand: "1xbet",
    img: "",
  },
  "1xbet:ug": {
    bookie: "1xbet:ug",
    from: "1",
    to: "1",
    name: "1xbet -Uganda",
    brand: "1xbet",
    img: "",
  },
  "1xbet:xx": {
    bookie: "1xbet:xx",
    from: "1",
    to: "1",
    name: "1xbet -Global",
    brand: "1xbet",
    img: "",
  },
  "1xbet:zm": {
    bookie: "1xbet:zm",
    from: "1",
    to: "1",
    name: "1xbet -Zambia",
    brand: "1xbet",
    img: "",
  },
  "1xbit": {
    bookie: "1xbit",
    from: "1",
    to: "1",
    name: "1xbit ",
    brand: "1xbit",
    img: "",
  },
  "22bet": {
    bookie: "22bet",
    from: "1",
    to: "1",
    name: "22bet ",
    brand: "22bet",
    img: "",
  },
  "888starz:xx": {
    bookie: "888starz:xx",
    from: "1",
    to: "1",
    name: "888starz -Global",
    brand: "888starz",
    img: "",
  },
  bangbet: {
    bookie: "bangbet",
    from: "1",
    to: "1",
    name: "bangbet ",
    brand: "bangbet",
    img: "",
  },
  bet9ja: {
    bookie: "bet9ja",
    from: "1",
    to: "1",
    name: "bet9ja ",
    brand: "bet9ja",
    img: "",
  },
  "betafriq:ke": {
    bookie: "betafriq:ke",
    from: "1",
    to: "1",
    name: "betafriq -Kenya",
    brand: "betafriq",
    img: "",
  },
  betandyou: {
    bookie: "betandyou",
    from: "1",
    to: "1",
    name: "betandyou ",
    brand: "betandyou",
    img: "",
  },
  "betika:et": {
    bookie: "betika:et",
    from: "1",
    to: "1",
    name: "betika -Ethiopia",
    brand: "betika",
    img: "",
  },
  "betika:gh": {
    bookie: "betika:gh",
    from: "1",
    to: "1",
    name: "betika -Ghana",
    brand: "betika",
    img: "",
  },
  "betika:ke": {
    bookie: "betika:ke",
    from: "1",
    to: "1",
    name: "betika -Kenya",
    brand: "betika",
    img: "",
  },
  "betika:mz": {
    bookie: "betika:mz",
    from: "1",
    to: "1",
    name: "betika -Mozambique",
    brand: "betika",
    img: "",
  },
  "betika:ng": {
    bookie: "betika:ng",
    from: "1",
    to: "1",
    name: "betika -Nigeria",
    brand: "betika",
    img: "",
  },
  "betika:tz": {
    bookie: "betika:tz",
    from: "1",
    to: "1",
    name: "betika -Tanzania",
    brand: "betika",
    img: "",
  },
  "betika:zm": {
    bookie: "betika:zm",
    from: "1",
    to: "1",
    name: "betika -Zambia",
    brand: "betika",
    img: "",
  },
  "betking:ng": {
    bookie: "betking:ng",
    from: "1",
    to: "1",
    name: "betking -Nigeria",
    brand: "betking",
    img: "",
  },
  betpawa: {
    bookie: "betpawa",
    from: "1",
    to: "1",
    name: "betpawa ",
    brand: "betpawa",
    img: "",
  },
  "betway:ke": {
    bookie: "betway:ke",
    from: "1",
    to: "1",
    name: "betway -Kenya",
    brand: "betway",
    img: "",
  },
  "betway:ng": {
    bookie: "betway:ng",
    from: "1",
    to: "1",
    name: "betway -Nigeria",
    brand: "betway",
    img: "",
  },
  "betway:za": {
    bookie: "betway:za",
    from: "1",
    to: "1",
    name: "betway -South Africa",
    brand: "betway",
    img: "",
  },
  "betway:zm": {
    bookie: "betway:zm",
    from: "1",
    to: "1",
    name: "betway -Zambia",
    brand: "betway",
    img: "",
  },
  "betway_new:gh": {
    bookie: "betway_new:gh",
    from: "1",
    to: "1",
    name: "Betway (-new) -Ghana",
    brand: "Betway (-new)",
    img: "",
  },
  betwinner: {
    bookie: "betwinner",
    from: "1",
    to: "1",
    name: "betwinner ",
    brand: "betwinner",
    img: "",
  },
  "betwinner:ng": {
    bookie: "betwinner:ng",
    from: "1",
    to: "1",
    name: "betwinner -Nigeria",
    brand: "betwinner",
    img: "",
  },
  db_bet: {
    bookie: "db_bet",
    from: "1",
    to: "1",
    name: "db bet ",
    brand: "db_bet",
    img: "",
  },
  "fansport:ng": {
    bookie: "fansport:ng",
    from: "1",
    to: "1",
    name: "fansport -Nigeria",
    brand: "fansport",
    img: "",
  },
  helabet: {
    bookie: "helabet",
    from: "1",
    to: "1",
    name: "helabet ",
    brand: "helabet",
    img: "",
  },
  linebet: {
    bookie: "linebet",
    from: "1",
    to: "1",
    name: "linebet ",
    brand: "linebet",
    img: "",
  },
  "livescorebet:ng": {
    bookie: "livescorebet:ng",
    from: "1",
    to: "0",
    name: "livescorebet -Nigeria",
    brand: "livescorebet",
    img: "",
  },
  megapari: {
    bookie: "megapari",
    from: "1",
    to: "1",
    name: "megapari ",
    brand: "megapari",
    img: "",
  },
  melbet: {
    bookie: "melbet",
    from: "1",
    to: "1",
    name: "melbet ",
    brand: "melbet",
    img: "",
  },
  merrybet: {
    bookie: "merrybet",
    from: "1",
    to: "0",
    name: "merrybet ",
    brand: "merrybet",
    img: "",
  },
  msport: {
    bookie: "msport",
    from: "1",
    to: "1",
    name: "msport ",
    brand: "msport",
    img: "",
  },
  nairabet: {
    bookie: "nairabet",
    from: "1",
    to: "1",
    name: "nairabet ",
    brand: "nairabet",
    img: "",
  },
  "odibet:gh": {
    bookie: "odibet:gh",
    from: "1",
    to: "1",
    name: "odibet -Ghana",
    brand: "odibet",
    img: "",
  },
  "odibet:ke": {
    bookie: "odibet:ke",
    from: "1",
    to: "1",
    name: "odibet -Kenya",
    brand: "odibet",
    img: "",
  },
  paripesa: {
    bookie: "paripesa",
    from: "1",
    to: "1",
    name: "paripesa ",
    brand: "paripesa",
    img: "",
  },
  "sportybet:br": {
    bookie: "sportybet:br",
    from: "1",
    to: "1",
    name: "sportybet -Brazil",
    brand: "sportybet",
    img: "",
  },
  "sportybet:gh": {
    bookie: "sportybet:gh",
    from: "1",
    to: "1",
    name: "sportybet -Ghana",
    brand: "sportybet",
    img: "",
  },
  "sportybet:ng": {
    bookie: "sportybet:ng",
    from: "1",
    to: "1",
    name: "sportybet -Nigeria",
    brand: "sportybet",
    img: "",
  },
  "sportybet:tz": {
    bookie: "sportybet:tz",
    from: "1",
    to: "1",
    name: "sportybet -Tanzania",
    brand: "sportybet",
    img: "",
  },
  "sportybet:ug": {
    bookie: "sportybet:ug",
    from: "1",
    to: "1",
    name: "sportybet -Uganda",
    brand: "sportybet",
    img: "",
  },
  "sportybet:zm": {
    bookie: "sportybet:zm",
    from: "1",
    to: "1",
    name: "sportybet -Zambia",
    brand: "sportybet",
    img: "",
  },
};

let bookiesArr: {}[] = [];

for (const item of Object.entries(bookies)) {
  bookiesArr.push(item[1]);
}

console.log(bookiesArr);

fs.writeFileSync("bookies.ts", JSON.stringify(bookiesArr), "utf-8");
