export const bookies = [
  {
    bookie: "1xbet:bj",
    from: "1",
    to: "1",
    name: "1xbet -Benin",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbet:ci",
    from: "1",
    to: "1",
    name: "1xbet -Côte d'Ivoire",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbet:cm",
    from: "1",
    to: "1",
    name: "1xbet -Cameroon",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbet:gh",
    from: "1",
    to: "1",
    name: "1xbet -Ghana",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbet:ke",
    from: "1",
    to: "1",
    name: "1xbet -Kenya",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbet:mw",
    from: "1",
    to: "1",
    name: "1xbet -Malawi",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbet:ng",
    from: "1",
    to: "1",
    name: "1xbet -Nigeria",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbet:ug",
    from: "1",
    to: "1",
    name: "1xbet -Uganda",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbet:xx",
    from: "1",
    to: "1",
    name: "1xbet -Global",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbet:zm",
    from: "1",
    to: "1",
    name: "1xbet -Zambia",
    brand: "1xbet",
    img: "",
  },
  {
    bookie: "1xbit",
    from: "1",
    to: "1",
    name: "1xbit ",
    brand: "1xbit",
    img: "",
  },
  {
    bookie: "22bet",
    from: "1",
    to: "1",
    name: "22bet ",
    brand: "22bet",
    img: "",
  },
  {
    bookie: "888starz:xx",
    from: "1",
    to: "1",
    name: "888starz -Global",
    brand: "888starz",
    img: "",
  },
  {
    bookie: "bangbet",
    from: "1",
    to: "1",
    name: "bangbet ",
    brand: "bangbet",
    img: "",
  },
  {
    bookie: "bet9ja",
    from: "1",
    to: "1",
    name: "bet9ja ",
    brand: "bet9ja",
    img: "",
  },
  {
    bookie: "betafriq:ke",
    from: "1",
    to: "1",
    name: "betafriq -Kenya",
    brand: "betafriq",
    img: "",
  },
  {
    bookie: "betandyou",
    from: "1",
    to: "1",
    name: "betandyou ",
    brand: "betandyou",
    img: "",
  },
  {
    bookie: "betika:et",
    from: "1",
    to: "1",
    name: "betika -Ethiopia",
    brand: "betika",
    img: "",
  },
  {
    bookie: "betika:gh",
    from: "1",
    to: "1",
    name: "betika -Ghana",
    brand: "betika",
    img: "",
  },
  {
    bookie: "betika:ke",
    from: "1",
    to: "1",
    name: "betika -Kenya",
    brand: "betika",
    img: "",
  },
  {
    bookie: "betika:mz",
    from: "1",
    to: "1",
    name: "betika -Mozambique",
    brand: "betika",
    img: "",
  },
  {
    bookie: "betika:ng",
    from: "1",
    to: "1",
    name: "betika -Nigeria",
    brand: "betika",
    img: "",
  },
  {
    bookie: "betika:tz",
    from: "1",
    to: "1",
    name: "betika -Tanzania",
    brand: "betika",
    img: "",
  },
  {
    bookie: "betika:zm",
    from: "1",
    to: "1",
    name: "betika -Zambia",
    brand: "betika",
    img: "",
  },
  {
    bookie: "betking:ng",
    from: "1",
    to: "1",
    name: "betking -Nigeria",
    brand: "betking",
    img: "",
  },
  {
    bookie: "betpawa",
    from: "1",
    to: "1",
    name: "betpawa ",
    brand: "betpawa",
    img: "",
  },
  {
    bookie: "betway:ke",
    from: "1",
    to: "1",
    name: "betway -Kenya",
    brand: "betway",
    img: "",
  },
  {
    bookie: "betway:ng",
    from: "1",
    to: "1",
    name: "betway -Nigeria",
    brand: "betway",
    img: "",
  },
  {
    bookie: "betway:za",
    from: "1",
    to: "1",
    name: "betway -South Africa",
    brand: "betway",
    img: "",
  },
  {
    bookie: "betway:zm",
    from: "1",
    to: "1",
    name: "betway -Zambia",
    brand: "betway",
    img: "",
  },
  {
    bookie: "betway_new:gh",
    from: "1",
    to: "1",
    name: "Betway (-new) -Ghana",
    brand: "Betway (-new)",
    img: "",
  },
  {
    bookie: "betwinner",
    from: "1",
    to: "1",
    name: "betwinner ",
    brand: "betwinner",
    img: "",
  },
  {
    bookie: "betwinner:ng",
    from: "1",
    to: "1",
    name: "betwinner -Nigeria",
    brand: "betwinner",
    img: "",
  },
  {
    bookie: "db_bet",
    from: "1",
    to: "1",
    name: "db bet ",
    brand: "db_bet",
    img: "",
  },
  {
    bookie: "fansport:ng",
    from: "1",
    to: "1",
    name: "fansport -Nigeria",
    brand: "fansport",
    img: "",
  },
  {
    bookie: "helabet",
    from: "1",
    to: "1",
    name: "helabet ",
    brand: "helabet",
    img: "",
  },
  {
    bookie: "linebet",
    from: "1",
    to: "1",
    name: "linebet ",
    brand: "linebet",
    img: "",
  },
  {
    bookie: "livescorebet:ng",
    from: "1",
    to: "0",
    name: "livescorebet -Nigeria",
    brand: "livescorebet",
    img: "",
  },
  {
    bookie: "megapari",
    from: "1",
    to: "1",
    name: "megapari ",
    brand: "megapari",
    img: "",
  },
  {
    bookie: "melbet",
    from: "1",
    to: "1",
    name: "melbet ",
    brand: "melbet",
    img: "",
  },
  {
    bookie: "merrybet",
    from: "1",
    to: "0",
    name: "merrybet ",
    brand: "merrybet",
    img: "",
  },
  {
    bookie: "msport",
    from: "1",
    to: "1",
    name: "msport ",
    brand: "msport",
    img: "",
  },
  {
    bookie: "nairabet",
    from: "1",
    to: "1",
    name: "nairabet ",
    brand: "nairabet",
    img: "",
  },
  {
    bookie: "odibet:gh",
    from: "1",
    to: "1",
    name: "odibet -Ghana",
    brand: "odibet",
    img: "",
  },
  {
    bookie: "odibet:ke",
    from: "1",
    to: "1",
    name: "odibet -Kenya",
    brand: "odibet",
    img: "",
  },
  {
    bookie: "paripesa",
    from: "1",
    to: "1",
    name: "paripesa ",
    brand: "paripesa",
    img: "",
  },
  {
    bookie: "sportybet:br",
    from: "1",
    to: "1",
    name: "sportybet -Brazil",
    brand: "sportybet",
    img: "",
  },
  {
    bookie: "sportybet:gh",
    from: "1",
    to: "1",
    name: "sportybet -Ghana",
    brand: "sportybet",
    img: "",
  },
  {
    bookie: "sportybet:ng",
    from: "1",
    to: "1",
    name: "sportybet -Nigeria",
    brand: "sportybet",
    img: "",
  },
  {
    bookie: "sportybet:tz",
    from: "1",
    to: "1",
    name: "sportybet -Tanzania",
    brand: "sportybet",
    img: "",
  },
  {
    bookie: "sportybet:ug",
    from: "1",
    to: "1",
    name: "sportybet -Uganda",
    brand: "sportybet",
    img: "",
  },
  {
    bookie: "sportybet:zm",
    from: "1",
    to: "1",
    name: "sportybet -Zambia",
    brand: "sportybet",
    img: "",
  },
];
