export const teams = [
  {
    id: 1,
    sport_id: 1,
    category_id: 40,
    venue_id: 1,
    manager_id: 1837,
    slug: "southampton",
    name: "Southampton",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/southampton.png",
    name_translations: {
      en: "Southampton",
      ru: "Саутгемптон",
      de: "Southampton FC",
      es: "Southampton FC",
      fr: "Southampton FC",
      zh: "南安普敦",
      tr: "Southampton",
      el: "Σαουθάμπτον",
      it: "Southampton",
      nl: "Southampton FC",
      pt: "Southampton FC",
    },
    name_short: "Southampton",
    name_full: "Southampton",
    name_code: "SOU",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ENG",
    country: "England",
    flag: "england",
    foundation: null,
    details: null,
  },
  {
    id: 2,
    sport_id: 1,
    category_id: 40,
    venue_id: 2,
    manager_id: 5265,
    slug: "burnley",
    name: "Burnley",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/burnley.png",
    name_translations: {
      en: "Burnley",
      ru: "Бернли",
      de: "Burnley FC",
      es: "Burnley FC",
      fr: "Burnley FC",
      zh: "伯恩利",
      tr: "Burnley",
      el: "Μπέρνλι",
      it: "Burnley",
      nl: "Burnley FC",
      pt: "Burnley FC",
    },
    name_short: "Burnley",
    name_full: "Burnley",
    name_code: "BUR",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ENG",
    country: "England",
    flag: "england",
    foundation: null,
    details: null,
  },
  {
    id: 3,
    sport_id: 1,
    category_id: 40,
    venue_id: 3,
    manager_id: 64,
    slug: "norwich-city",
    name: "Norwich City",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/norwich-city.png",
    name_translations: {
      en: "Norwich City",
      ru: "Норвич Сити",
      de: "Norwich City FC",
      es: "Norwich City FC",
      fr: "Norwich City FC",
      zh: "诺维奇",
      tr: "Norwich City FC",
      el: "Νόργουιτς",
      it: "Norwich",
      nl: "Norwich City FC",
      pt: "Norwich City FC",
    },
    name_short: "Norwich",
    name_full: "Norwich City",
    name_code: "NOR",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ENG",
    country: "England",
    flag: "england",
    foundation: null,
    details: null,
  },
  {
    id: 4,
    sport_id: 1,
    category_id: 40,
    venue_id: 4,
    manager_id: 4,
    slug: "liverpool",
    name: "Liverpool",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/liverpool.png",
    name_translations: {
      en: "Liverpool",
      ru: "Ливерпуль",
      de: "Liverpool FC",
      es: "Liverpool FC",
      fr: "Liverpool FC",
      zh: "利物浦",
      tr: "Liverpool",
      el: "Λίβερπουλ",
      it: "Liverpool",
      nl: "Liverpool FC",
      pt: "Liverpool FC",
    },
    name_short: "Liverpool",
    name_full: "Liverpool",
    name_code: "LIV",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ENG",
    country: "England",
    flag: "england",
    foundation: null,
    details: null,
  },
  {
    id: 5,
    sport_id: 1,
    category_id: 40,
    venue_id: 5,
    manager_id: 5069,
    slug: "aston-villa",
    name: "Aston Villa",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/aston-villa.png",
    name_translations: {
      en: "Aston Villa",
      ru: "Астон Вилла",
      de: "Aston Villa Birmingham FC",
      es: "Aston Villa",
      fr: "Aston Villa",
      zh: "阿斯顿维拉",
      tr: "Aston Villa",
      el: "Άστον Βίλα",
      it: "Aston Villa",
      nl: "Aston Villa",
      pt: "Aston Villa FC",
    },
    name_short: "Aston Villa",
    name_full: "Aston Villa",
    name_code: "AVL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ENG",
    country: "England",
    flag: "england",
    foundation: null,
    details: null,
  },
  {
    id: 6,
    sport_id: 1,
    category_id: 40,
    venue_id: 6,
    manager_id: 3286,
    slug: "tottenham",
    name: "Tottenham Hotspur",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/tottenham.png",
    name_translations: {
      en: "Tottenham Hotspur",
      ru: "Тоттенхэм Хотспур",
      de: "Tottenham Hotspur",
      es: "Tottenham Hotspur FC",
      fr: "Tottenham Hotspur FC",
      zh: "托特纳姆",
      tr: "Tottenham",
      el: "Τότεναμ",
      it: "Tottenham",
      nl: "Tottenham Hotspur FC",
      pt: "Tottenham Hotspur FC",
    },
    name_short: "Tottenham ",
    name_full: "Tottenham Hotspur",
    name_code: "TOT",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ENG",
    country: "England",
    flag: "england",
    foundation: null,
    details: null,
  },
  {
    id: 7,
    sport_id: 1,
    category_id: 40,
    venue_id: 7,
    manager_id: 7,
    slug: "arsenal",
    name: "Arsenal",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/arsenal.png",
    name_translations: {
      en: "Arsenal",
      ru: "Арсенал",
      de: "Arsenal FC",
      es: "Arsenal FC",
      fr: "Football Club d´Arsenal",
      zh: "阿森纳",
      tr: "Arsenal FC",
      el: "Άρσεναλ",
      it: "Arsenal FC",
      nl: "Arsenal FC",
      pt: "Arsenal FC",
    },
    name_short: "Arsenal",
    name_full: "Arsenal",
    name_code: "ARS",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ENG",
    country: "England",
    flag: "england",
    foundation: null,
    details: null,
  },
  {
    id: 8,
    sport_id: 1,
    category_id: 40,
    venue_id: 8,
    manager_id: 1828,
    slug: "newcastle-united",
    name: "Newcastle United",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/newcastle-united.png",
    name_translations: {
      en: "Newcastle United",
      ru: "Ньюкасл Юнайтед",
      de: "Newcastle United FC",
      es: "Newcastle United FC",
      fr: "Newcastle United FC",
      zh: "纽卡斯尔",
      tr: "Newcastle United FC",
      el: "Νιουκάστλ",
      it: "Newcastle United FC",
      nl: "Newcastle United FC",
      pt: "Newcastle United FC",
    },
    name_short: "Newcastle",
    name_full: "Newcastle United",
    name_code: "NEW",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ENG",
    country: "England",
    flag: "england",
    foundation: null,
    details: null,
  },
  {
    id: 9,
    sport_id: 1,
    category_id: 32,
    venue_id: 9,
    manager_id: 19,
    slug: "rcd-mallorca",
    name: "Mallorca",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/rcd-mallorca.png",
    name_translations: {
      en: "Mallorca",
      ru: "Мальорка",
      de: "RCD Mallorca",
      es: "RCD Mallorca",
      fr: "Majorque",
      zh: "皇家马略卡",
      tr: "Real Mallorca",
      el: "Μαγιόρκα",
      it: "RCD Maiorca",
      nl: "RCD Mallorca",
      pt: "RCD Mallorca",
    },
    name_short: "Mallorca",
    name_full: "Mallorca",
    name_code: "MLL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 10,
    sport_id: 1,
    category_id: 32,
    venue_id: 10,
    manager_id: 1203,
    slug: "deportivo-alaves",
    name: "Deportivo Alavés",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/deportivo-alaves.png",
    name_translations: {
      en: "Deportivo Alavés",
      ru: "Алавес",
      de: "Deportivo Alaves",
      es: "Deportivo Alavés",
      fr: "Deportivo Alaves",
      zh: "阿拉维斯",
      tr: "Alaves",
      el: "Αλαβές",
      it: "Alavés",
      nl: "Deportivo Alavés",
      pt: "Deportivo Alavés",
    },
    name_short: "Alavés",
    name_full: "Deportivo Alavés",
    name_code: "ALA",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 11,
    sport_id: 1,
    category_id: 32,
    venue_id: 20102,
    manager_id: 645,
    slug: "barcelona",
    name: "Barcelona",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/barcelona.png",
    name_translations: {
      en: "Barcelona",
      ru: "Барселона",
      de: "FC Barcelona",
      es: "FC Barcelona",
      fr: "FC Barcelone",
      zh: "巴塞罗那",
      tr: "FC Barcelona",
      el: "Μπαρτσελόνα",
      it: "Barcellona",
      nl: "FC Barcelona",
      pt: "FC Barcelona",
    },
    name_short: "Barcelona",
    name_full: "Barcelona",
    name_code: "FCB",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 12,
    sport_id: 1,
    category_id: 32,
    venue_id: 12,
    manager_id: 12,
    slug: "getafe",
    name: "Getafe",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/getafe.png",
    name_translations: {
      en: "Getafe",
      ru: "Хетафе",
      de: "Getafe CF",
      es: "Getafe CF",
      fr: "Getafe CF",
      zh: "赫塔费",
      tr: "Getafe",
      el: "Χετάφε",
      it: "Getafe",
      nl: "Getafe CF",
      pt: "Getafe CF",
    },
    name_short: "Getafe",
    name_full: "Getafe",
    name_code: "GET",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: "1983-07-08 00:00:00",
    details: null,
  },
  {
    id: 13,
    sport_id: 1,
    category_id: 32,
    venue_id: 13,
    manager_id: 1305,
    slug: "villarreal",
    name: "Villarreal",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/villarreal.png",
    name_translations: {
      en: "Villarreal",
      ru: "Вильярреал",
      de: "Villarreal CF",
      es: "Villarreal CF",
      fr: "Villarreal CF",
      zh: "维拉里尔",
      tr: "Villarreal CF",
      el: "Βιγιαρεάλ",
      it: "Villarreal CF",
      nl: "Villarreal CF",
      pt: "Villarreal CF",
    },
    name_short: "Villarreal",
    name_full: "Villarreal",
    name_code: "VIL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 14,
    sport_id: 1,
    category_id: 32,
    venue_id: 14,
    manager_id: 13,
    slug: "levante",
    name: "Levante UD",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/levante.png",
    name_translations: {
      en: "Levante UD",
      ru: "Леванте",
      de: "Levante UD",
      es: "Levante UD",
      fr: "Levante UD",
      zh: "莱万特",
      tr: "Levante",
      el: "Λεβάντε",
      it: "Levante",
      nl: "Levante UD",
      pt: "Levante UD",
    },
    name_short: "Levante",
    name_full: "Levante UD",
    name_code: "LEV",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 15,
    sport_id: 1,
    category_id: 32,
    venue_id: 15,
    manager_id: 14,
    slug: "granada",
    name: "Granada",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/granada.png",
    name_translations: {
      en: "Granada",
      ru: "Гранада",
      de: "Granada CF",
      es: "Granada CF",
      fr: "Grenade CF",
      zh: "格拉纳达",
      tr: "Granada CF",
      el: "Γρανάδα",
      it: "Granada",
      nl: "Granada CF",
      pt: "Granada CF",
    },
    name_short: "Granada",
    name_full: "Granada",
    name_code: "GCF",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 16,
    sport_id: 1,
    category_id: 32,
    venue_id: 16,
    manager_id: 3405,
    slug: "real-valladolid",
    name: "Real Valladolid",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/real-valladolid.png",
    name_translations: {
      en: "Real Valladolid",
      ru: "Реал Вальядолид",
      de: "Real Valladolid",
      es: "Real Valladolid",
      fr: "Real Valladolid",
      zh: "巴拉多利德",
      tr: "Real Valladolid",
      el: "Βαγιαδολίδ",
      it: "Real Valladolid",
      nl: "Real Valladolid",
      pt: "Real Valladolid",
    },
    name_short: "Real Valladolid",
    name_full: "Real Valladolid",
    name_code: "VLL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 17,
    sport_id: 1,
    category_id: 32,
    venue_id: 17,
    manager_id: 557,
    slug: "sevilla",
    name: "Sevilla",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/sevilla.png",
    name_translations: {
      en: "Sevilla",
      ru: "Cевилья",
      de: "Sevilla FC",
      es: "Sevilla FC",
      fr: "FC Séville",
      zh: "塞维利亚",
      tr: "Sevilla",
      el: "Σεβίλλη",
      it: "Siviglia",
      nl: "Sevilla FC",
      pt: "Sevilha FC",
    },
    name_short: "Sevilla",
    name_full: "Sevilla",
    name_code: "SEV",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 18,
    sport_id: 1,
    category_id: 32,
    venue_id: 18,
    manager_id: 11270,
    slug: "espanyol",
    name: "Espanyol",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/espanyol.png",
    name_translations: {
      en: "Espanyol",
      ru: "Эспаньол",
      de: "RCD Espanyol Barcelona",
      es: "RCD Espanyol Barcelona",
      fr: "Espanyol Barcelone",
      zh: "西班牙人",
      tr: "Espanyol Barcelona",
      el: "Εσπανιόλ",
      it: "Espanyol Barcellona",
      nl: "RCD Espanyol",
      pt: "RCD Espanhol de Barcelona",
    },
    name_short: "Espanyol",
    name_full: "Espanyol",
    name_code: "ESP",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 19,
    sport_id: 1,
    category_id: 32,
    venue_id: 19,
    manager_id: 1386,
    slug: "leganes",
    name: "Leganés",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/leganes.png",
    name_translations: {
      en: "Leganés",
      ru: "Леганес",
      de: "CD Leganés",
      es: "CD Leganés",
      fr: "CD Leganes",
      zh: "雷加利斯",
      tr: "CD Leganes",
      el: "Λεγκανές",
      it: "Leganes",
      nl: "CD Leganés",
      pt: "CD Leganés",
    },
    name_short: "Leganés",
    name_full: "Leganés",
    name_code: "LEG",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 20,
    sport_id: 1,
    category_id: 32,
    venue_id: 20,
    manager_id: 5176,
    slug: "real-betis",
    name: "Real Betis",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/real-betis.png",
    name_translations: {
      en: "Real Betis",
      ru: "Реал Бетис",
      de: "Real Betis Balompie",
      es: "Real Betis Balompié",
      fr: "Real Betis Balompié",
      zh: "皇家贝蒂斯",
      tr: "Real Betis Sevilla",
      el: "Μπέτις",
      it: "Real Betis",
      nl: "Betis Sevilla",
      pt: "Bétis",
    },
    name_short: "Betis",
    name_full: "Real Betis",
    name_code: "RBB",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 21,
    sport_id: 1,
    category_id: 32,
    venue_id: 21,
    manager_id: 1437,
    slug: "eibar",
    name: "Eibar",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/eibar.png",
    name_translations: {
      en: "Eibar",
      ru: "Эйбар",
      de: "SD Eibar",
      es: "SD Eibar",
      fr: "SD Eibar",
      zh: "埃瓦尔",
      tr: "Eibar",
      el: "Έιμπαρ",
      it: "Eibar",
      nl: "SD Eibar",
      pt: "SD Eibar",
    },
    name_short: "Eibar",
    name_full: "Eibar",
    name_code: "EIB",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 22,
    sport_id: 1,
    category_id: 32,
    venue_id: 22,
    manager_id: 22,
    slug: "real-sociedad",
    name: "Real Sociedad",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/real-sociedad.png",
    name_translations: {
      en: "Real Sociedad",
      ru: "Реал Сосьедад",
      de: "Real Sociedad",
      es: "Real Sociedad",
      fr: "Real Sociedad",
      zh: "皇家社会",
      tr: "Real Sociedad San Sebastian",
      el: "Σοσιεδάδ",
      it: "Real Sociedad",
      nl: "Real Sociedad",
      pt: "Real Sociedad",
    },
    name_short: "Real Sociedad",
    name_full: "Real Sociedad",
    name_code: "RSO",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 23,
    sport_id: 1,
    category_id: 32,
    venue_id: 23,
    manager_id: 9428,
    slug: "athletic-bilbao",
    name: "Athletic Club",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/athletic-bilbao.png",
    name_translations: {
      en: "Athletic Club",
      ru: "Атлетик Бильбао",
      de: "Athletic Bilbao",
      es: "Athletic Bilbao",
      fr: "Athletic Bilbao",
      zh: "毕尔巴鄂竞技",
      tr: "Athletic de Bilbao",
      el: "Αθλέτικ Μπιλμπάο",
      it: "Athletic Bilbao",
      nl: "Athletic Bilbao",
      pt: "Atlético de Bilbao",
    },
    name_short: "Athletic Club",
    name_full: "Athletic Club",
    name_code: "ATH",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 24,
    sport_id: 1,
    category_id: 32,
    venue_id: 24,
    manager_id: 24,
    slug: "osasuna",
    name: "Osasuna",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/osasuna.png",
    name_translations: {
      en: "Osasuna",
      ru: "Осасуна",
      de: "CA Osasuna",
      es: "CA Osasuna",
      fr: "CA Osasuna",
      zh: "奥萨苏纳",
      tr: "CA Osasuna",
      el: "Οσασούνα",
      it: "Osasuna",
      nl: "CA Osasuna",
      pt: "CA Osasuna",
    },
    name_short: "Osasuna",
    name_full: "Osasuna",
    name_code: "OSA",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: null,
  },
  {
    id: 25,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "ruud-c",
    name: "Ruud C.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/ruud-c.png",
    name_translations: {
      en: "Ruud C.",
      ru: "Рууд, Каспер",
      es: "Ruud, Casper",
      fr: "Ruud, Casper",
      zh: "鲁德, 卡斯珀",
      el: "Ράουντ, Κάσπερ",
      pt: "Casper Ruud",
    },
    name_short: "Ruud C.",
    name_full: "Ruud, Casper",
    name_code: "RUU",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "NOR",
    country: "Norway",
    flag: "norway",
    foundation: null,
    details: {
      country: "Norway",
      country_i_s_o: "NOR",
      date_of_birth: "24 (22 Dec 1998)",
      birthplace: "Oslo, Norway",
      plays: "Right-Handed",
      residence: "Oslo, Norway",
      weight: "77 kg",
      height_meters: 1.83,
      prize_current: "2.5M €",
      prize_total: "13.4M €",
      prize_current_euros: 2536148,
      prize_total_euros: 13435581,
      flag: "norway",
    },
  },
  {
    id: 26,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "londero-j",
    name: "Londero J.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/londero-j.png",
    name_translations: {
      en: "Londero J.",
      ru: "Хуан Игнасио Лондера",
      de: "Londero, Juan Ignacio",
      es: "Londero, Juan Ignacio",
      fr: "Londero, Juan Ignacio",
      zh: "隆德罗",
      el: "Λοντέρο, Ζουάν Ιγκνάσιο",
      pt: "Juan Ignacio Londero",
      it: "Londero, Juan Ignacio",
    },
    name_short: "Londero J.",
    name_full: "Londero, Juan Ignacio",
    name_code: "LJI",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: {
      country: "Argentina",
      country_i_s_o: "ARG",
      date_of_birth: "30 (15 Aug 1993)",
      birthplace: "Jesus Maria, Argentina",
      plays: "Right-Handed",
      residence: "Buenos Aires, Argentina",
      weight: "70 kg",
      height_meters: 1.8,
      prize_current: "7.7k €",
      prize_total: "1.8M €",
      prize_current_euros: 7733,
      prize_total_euros: 1760558,
      flag: "argentina",
    },
  },
  {
    id: 27,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "schwartzman-d",
    name: "Schwartzman D.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/schwartzman-d.png",
    name_translations: {
      en: "Schwartzman D.",
      ru: "Шварцман, Диего",
      de: "Schwartzman, Diego",
      es: "Schwartzman, Diego",
      zh: "施瓦茨曼, 迭戈",
      el: "Σβαρτζμάν, Ντιέγκο Σεμπάστιαν",
      pt: "Diego Schwartzman",
      fr: "Schwartzman, Diego",
      it: "Schwartzman, Diego",
    },
    name_short: "Schwartzman D.",
    name_full: "Schwartzman, Diego",
    name_code: "SWM",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: {
      country: "Argentina",
      country_i_s_o: "ARG",
      date_of_birth: "31 (16 Aug 1992)",
      birthplace: "Buenos Aires, Argentina",
      plays: "Right-Handed",
      residence: "Buenos Aires, Argentina",
      weight: "64 kg",
      height_meters: 1.7,
      prize_current: "805.3k €",
      prize_total: "11.6M €",
      prize_current_euros: 805326,
      prize_total_euros: 11580948,
      flag: "argentina",
    },
  },
  {
    id: 28,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "sousa-p",
    name: "Sousa P.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/sousa-p.png",
    name_translations: {
      en: "Sousa P.",
      ru: "Соуза, Педро",
      es: "Sousa, Pedro",
      fr: "Sousa, Pedro",
      zh: "索萨，佩德罗",
      el: "Σούσα, Πέντρο",
      pt: "Pedro Sousa",
    },
    name_short: "Sousa P.",
    name_full: "Sousa, Pedro",
    name_code: "SOU",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "PRT",
    country: "Portugal",
    flag: "portugal",
    foundation: null,
    details: {
      country: "Portugal",
      country_i_s_o: "PRT",
      date_of_birth: "35 (27 May 1988)",
      birthplace: "Lisbon, Portugal",
      plays: "Right-Handed",
      residence: "Lisbon, Portugal",
      weight: "70 kg",
      height_meters: 1.8,
      prize_current: "16.2k €",
      prize_total: "932.5k €",
      prize_current_euros: 16182,
      prize_total_euros: 932479,
      flag: "portugal",
    },
  },
  {
    id: 29,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "cilic-m",
    name: "Čilić M.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/cilic-m.png",
    name_translations: {
      en: "Čilić M.",
      ru: "Чилич, Марин",
      es: "Cilic, Marin",
      zh: "西里奇，马琳",
      el: "Τσίλιτς, Μάριν",
      pt: "Marin Cilic",
      de: "Cilic, Marin",
      fr: "Cilic, Marin",
      it: "Cilic, Marin",
    },
    name_short: "Čilić M.",
    name_full: "Čilić, Marin",
    name_code: "CIL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "HRV",
    country: "Croatia",
    flag: "croatia",
    foundation: null,
    details: {
      country: "Croatia",
      country_i_s_o: "HRV",
      date_of_birth: "35 (28 Sep 1988)",
      birthplace: "Medjugorje, Bosnia-Herzegovina",
      plays: "Right-Handed",
      residence: "Monte Carlo, Monaco",
      weight: "89 kg",
      height_meters: 1.98,
      prize_current: "21.8k €",
      prize_total: "26M €",
      prize_current_euros: 21782,
      prize_total_euros: 26006151,
      flag: "croatia",
    },
  },
  {
    id: 30,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "krajinovic-f",
    name: "Krajinović F.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/krajinovic-f.png",
    name_translations: {
      en: "Krajinović F.",
      ru: "Филипп Краинович",
      es: "Krajinovic, Filip",
      zh: "克拉伊诺维奇, 菲利普",
      el: "Κραζίνοβιτς, Φίλιπ",
      pt: "Filip Krajinovic",
      de: "Krajinović, Filip",
    },
    name_short: "Krajinović F.",
    name_full: "Krajinović, Filip",
    name_code: "KRA",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "SRB",
    country: "Serbia",
    flag: "serbia",
    foundation: null,
    details: {
      country: "Serbia",
      country_i_s_o: "SRB",
      date_of_birth: "31 (27 Feb 1992)",
      birthplace: "Sombor, Serbia",
      plays: "Right-Handed",
      residence: "Belgrade, Serbia",
      weight: "75 kg",
      height_meters: 1.85,
      prize_current: "244.1k €",
      prize_total: "5.1M €",
      prize_current_euros: 244105,
      prize_total_euros: 5115793,
      flag: "serbia",
    },
  },
  {
    id: 31,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "kecmanovic-m",
    name: "Kecmanović M.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/kecmanovic-m.png",
    name_translations: {
      en: "Kecmanović M.",
      ru: "Кечманович, Миомир",
      es: "Kecmanovic, Miomir",
      fr: "Kecmanovic, Miomir",
      zh: "克奇马诺维奇,米奥米尔",
      el: "Κεσμάνοβικ, Μίομιρ",
      pt: "Miomir Kecmanovic",
      de: "Kecmanović, Miomir",
    },
    name_short: "Kecmanović M.",
    name_full: "Kecmanović, Miomir",
    name_code: "KEC",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "SRB",
    country: "Serbia",
    flag: "serbia",
    foundation: null,
    details: {
      country: "Serbia",
      country_i_s_o: "SRB",
      date_of_birth: "24 (31 Aug 1999)",
      birthplace: "Belgrade, Serbia",
      plays: "Right-Handed",
      residence: "Bradenton, FL, USA",
      weight: "75 kg",
      height_meters: 1.83,
      prize_current: "799.5k €",
      prize_total: "4.3M €",
      prize_current_euros: 799539,
      prize_total_euros: 4292047,
      flag: "serbia",
    },
  },
  {
    id: 32,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "edmund-k",
    name: "Edmund K.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/edmund-k.png",
    name_translations: {
      en: "Edmund K.",
      ru: "Кайл Эдмунд",
      es: "Edmund, Kyle",
      zh: "艾德蒙德，凯尔",
      el: "Εντμούντο, Κίλε",
      pt: "Kyle Edmund",
    },
    name_short: "Edmund K.",
    name_full: "Edmund, Kyle",
    name_code: "EDM",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "GBR",
    country: "United Kingdom",
    flag: "great-britain",
    foundation: null,
    details: {
      country: "United Kingdom",
      country_i_s_o: "GBR",
      date_of_birth: "28 (08 Jan 1995)",
      birthplace: "Johannesburg, South Africa",
      plays: "Right-Handed",
      residence: "Nassau, Bahamas",
      weight: "83 kg",
      height_meters: 1.88,
      prize_current: "126.3k €",
      prize_total: "5M €",
      prize_current_euros: 126273,
      prize_total_euros: 5016018,
      flag: "great-britain",
    },
  },
  {
    id: 33,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "seppi-a",
    name: "Seppi A.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/seppi-a.png",
    name_translations: {
      en: "Seppi A.",
      ru: "Сеппи, Андреас",
      es: "Seppi, Andreas",
      zh: "塞皮",
      el: "Σέπι, Αντρέας",
      pt: "Andreas Seppi",
    },
    name_short: "Seppi A.",
    name_full: "Seppi, Andreas",
    name_code: "SEP",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: {
      country: "Italy",
      country_i_s_o: "ITA",
      date_of_birth: "39 (21 Feb 1984)",
      birthplace: "Bolzano, Italy",
      plays: "Right-Handed",
      residence: "Caldaro, Italy",
      weight: "78 kg",
      height_meters: 1.91,
      prize_total: "9.8M €",
      prize_current_euros: 0,
      prize_total_euros: 9846843,
      flag: "italy",
    },
  },
  {
    id: 34,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "jung-j",
    name: "Jung J.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/jung-j.png",
    name_translations: {
      en: "Jung J.",
      ru: "Юнг, Джейсон",
      es: "Jung, Jason",
      zh: "荣格，杰森",
      el: "Ζούνγκ, Ζάσον",
      pt: "Jason Jung",
    },
    name_short: "Jung J.",
    name_full: "Jung, Jason",
    name_code: "JUN",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "TWN",
    country: "Chinese Taipei",
    flag: "taiwan",
    foundation: null,
    details: {
      country: "Chinese Taipei",
      country_i_s_o: "TWN",
      date_of_birth: "34 (15 Jun 1989)",
      birthplace: "Torrance, CA, USA",
      plays: "Right-Handed",
      residence: "Torrance, CA, USA",
      weight: "69 kg",
      height_meters: 1.8,
      prize_current: "52.4k €",
      prize_total: "952.6k €",
      prize_current_euros: 52433,
      prize_total_euros: 952635,
      flag: "taiwan",
    },
  },
  {
    id: 35,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "carreno-busta-p",
    name: "Carreño Busta P.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/carreno-busta-p.png",
    name_translations: {
      en: "Carreño Busta P.",
      ru: "Каррено-Буста, Пабло",
      es: "Carreño-Busta, Pablo",
      zh: "巴斯塔",
      el: "Καρένο-Μπούστα, Πάμπλο",
      pt: "Pablo Carrena-Busta",
      de: "Carreno Busta, Pablo",
    },
    name_short: "Carreño Busta P.",
    name_full: "Carreño Busta, Pablo",
    name_code: "CAR",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ESP",
    country: "Spain",
    flag: "spain",
    foundation: null,
    details: {
      country: "Spain",
      country_i_s_o: "ESP",
      date_of_birth: "32 (12 Jul 1991)",
      birthplace: "Gijon, Spain",
      plays: "Right-Handed",
      residence: "Barcelona, Spain",
      weight: "78 kg",
      height_meters: 1.88,
      prize_current: "119.2k €",
      prize_total: "12.7M €",
      prize_current_euros: 119216,
      prize_total_euros: 12708251,
      flag: "spain",
    },
  },
  {
    id: 36,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "auger-aliassime-f",
    name: "Auger-Aliassime F.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/auger-aliassime-f.png",
    name_translations: {
      en: "Auger-Aliassime F.",
      ru: "Оже-Альяссим, Феликс",
      de: "Auger-Aliassime, Félix",
      zh: "奥格尔·阿利亚西梅, 费利克斯",
      el: "Ογκέρ Αλιασίμ, Φέλιξ",
      pt: "Felix Auger Alliassime",
      fr: "Auger Aliassime, Félix",
      it: "Auger Aliassime, Felix",
      nl: "Auger Aliassime, Felix",
    },
    name_short: "Auger-Aliassime F.",
    name_full: "Auger-Aliassime, Felix",
    name_code: "AUG",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "CAN",
    country: "Canada",
    flag: "canada",
    foundation: null,
    details: {
      country: "Canada",
      country_i_s_o: "CAN",
      date_of_birth: "23 (08 Aug 2000)",
      birthplace: "Montreal, Canada",
      plays: "Right-Handed",
      residence: "Monte Carlo, Monaco",
      weight: "87 kg",
      height_meters: 1.93,
      prize_current: "965.7k €",
      prize_total: "9.5M €",
      prize_current_euros: 965703,
      prize_total_euros: 9533851,
      flag: "canada",
    },
  },
  {
    id: 37,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "monfils-g",
    name: "Monfils G.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/monfils-g.png",
    name_translations: {
      en: "Monfils G.",
      ru: "Монфис, Гаэль",
      es: "Monfils, Gael",
      zh: "蒙菲尔斯，盖尔",
      el: "Μονφίς, Γκάελ",
      pt: "Gael Monfils",
      fr: "Monfils, Gaël",
      it: "Monfils, Gael ",
    },
    name_short: "Monfils G.",
    name_full: "Monfils, Gaël",
    name_code: "MON",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "FRA",
    country: "France",
    flag: "france",
    foundation: null,
    details: {
      country: "France",
      country_i_s_o: "FRA",
      date_of_birth: "37 (01 Sep 1986)",
      birthplace: "Paris, France",
      plays: "Right-Handed",
      residence: "Switzerland",
      weight: "85 kg",
      height_meters: 1.93,
      prize_current: "567.1k €",
      prize_total: "18.1M €",
      prize_current_euros: 567139,
      prize_total_euros: 18053318,
      flag: "france",
    },
  },
  {
    id: 38,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "anisimova-a",
    name: "Anisimova A.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/anisimova-a.png",
    name_translations: {
      en: "Anisimova A.",
      ru: "Анисимова, Аманда",
      es: "Anisimova, Amanda",
      fr: "Anisimova, Amanda",
      zh: "阿尼伊莫娃, 阿曼达",
      el: "Ανισίμοβα, Αμάντα",
      pt: "Amanda Anisimova",
    },
    name_short: "Anisimova A.",
    name_full: "Anisimova, Amanda",
    name_code: "ANI",
    has_sub: false,
    gender: "F",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: {
      country: "USA",
      country_i_s_o: "USA",
      date_of_birth: "22 (31 Aug 2001)",
      birthplace: "Freehold, NJ, USA",
      plays: "Right-Handed",
      residence: "Aventura, FL, USA",
      weight: " kg",
      height_meters: 1.8,
      prize_current: "146.4k €",
      prize_total: "3.4M €",
      prize_current_euros: 146357,
      prize_total_euros: 3419883,
      flag: "usa",
    },
  },
  {
    id: 39,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "strycova-b",
    name: "Strýcová B.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/strycova-b.png",
    name_translations: {
      en: "Strýcová B.",
      ru: "Стрыцова, Барбора",
      es: "Strycova, Barbora",
      fr: "Srtycova, Barbora",
      zh: "斯特里措娃，巴尔博拉",
      el: "Στρίκοβα, Μπάρκοβα",
      pt: "Barbora Strycova",
    },
    name_short: "Strýcová B.",
    name_full: "Strýcová, Barbora",
    name_code: "STR",
    has_sub: false,
    gender: "F",
    is_nationality: false,
    country_code: "CZE",
    country: "Czech Republic",
    flag: "czech-republic",
    foundation: null,
    details: {
      country: "Czech Republic",
      country_i_s_o: "CZE",
      date_of_birth: "37 (28 Mar 1986)",
      birthplace: "Plzen, Czech Republic",
      plays: "Right-Handed",
      residence: "Dubai, UAE",
      weight: "60 kg",
      height_meters: 1.64,
      prize_current: "473.3k €",
      prize_total: "10.5M €",
      prize_current_euros: 473259,
      prize_total_euros: 10521205,
      flag: "czech-republic",
    },
  },
  {
    id: 40,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "clijsters-k",
    name: "Clijsters K.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/clijsters-k.png",
    name_translations: {
      en: "Clijsters K.",
      ru: "Ким Клийстерс",
      zh: "克里斯特尔斯",
      el: "Κλίστερς, Κιμ",
      pt: "Kim Clijsters",
      es: "Clusters, Kim",
    },
    name_short: "Clijsters K.",
    name_full: "Clijsters, Kim",
    name_code: "CLI",
    has_sub: false,
    gender: "F",
    is_nationality: false,
    country_code: "BEL",
    country: "Belgium",
    flag: "belgium",
    foundation: null,
    details: {
      country: "Belgium",
      country_i_s_o: "BEL",
      date_of_birth: "40 (08 Jun 1983)",
      birthplace: "Bilzen, Belgium",
      plays: "Right-Handed",
      weight: " kg",
      height_meters: 1.74,
      prize_total: "20.5M €",
      prize_current_euros: 0,
      prize_total_euros: 20454328,
      flag: "belgium",
    },
  },
  {
    id: 41,
    sport_id: 2,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "bertens-k",
    name: "Bertens K.",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/bertens-k.png",
    name_translations: {
      en: "Bertens K.",
      ru: "Бертенс, Кики",
      es: "Bertens, Kiki",
      fr: "Bertens, Kiki",
      zh: "贝尔滕斯，基基",
      el: "Μπέρτενς, Κικί",
      pt: "Kiki Bertens",
    },
    name_short: "Bertens K.",
    name_full: "Bertens, Kiki",
    name_code: "BER",
    has_sub: false,
    gender: "F",
    is_nationality: false,
    country_code: "NLD",
    country: "Netherlands",
    flag: "netherlands",
    foundation: null,
    details: {
      country: "Netherlands",
      country_i_s_o: "NLD",
      date_of_birth: "31 (10 Dec 1991)",
      birthplace: "Wateringen, Netherlands",
      plays: "Right-Handed",
      residence: "Wateringen, Netherlands",
      weight: "74 kg",
      height_meters: 1.82,
      prize_current: "9.7M €",
      prize_total: "9.7M €",
      prize_current_euros: 9710991,
      prize_total_euros: 9710992,
      flag: "netherlands",
    },
  },
  {
    id: 42,
    sport_id: 3,
    category_id: 168,
    venue_id: null,
    manager_id: 10094,
    slug: "team-giannis",
    name: "Team Giannis",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/team-giannis.png",
    name_translations: {
      en: "Team Giannis",
      ru: "Команда Giannis",
      zh: "扬尼斯队",
    },
    name_short: "Team Giannis",
    name_full: "Team Giannis",
    name_code: "GIAN",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 43,
    sport_id: 3,
    category_id: 168,
    venue_id: null,
    manager_id: 4936,
    slug: "team-lebron",
    name: "Team LeBron",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/team-lebron.png",
    name_translations: {
      en: "Team LeBron",
      ru: "Команда Lebron",
      zh: "勒布朗队",
      pt: "Equipa LeBron",
    },
    name_short: "Team LeBron",
    name_full: "Team LeBron",
    name_code: "LEB",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 44,
    sport_id: 3,
    category_id: 181,
    venue_id: 9800,
    manager_id: 9047,
    slug: "aris-bc",
    name: "Aris BC",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/aris-bc.png",
    name_translations: {
      en: "Aris BC",
      ru: "Арис",
      de: "BC Aris Thessaloniki",
      es: "Aris Salónica BC",
      zh: "阿里斯",
      el: "Άρης",
      nl: "BC Aris Thessaloniki",
      pt: "Aris Thessaloniki",
      fr: "Aris Salonique",
      tr: "Aris Thessaloniki",
    },
    name_short: "Aris",
    name_full: "Aris BC",
    name_code: "ARI",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "GRC",
    country: "Greece",
    flag: "greece",
    foundation: null,
    details: null,
  },
  {
    id: 45,
    sport_id: 3,
    category_id: 181,
    venue_id: 26,
    manager_id: 6269,
    slug: "panathinaikos-bc",
    name: "Panathinaikos BC",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/panathinaikos-bc.png",
    name_translations: {
      en: "Panathinaikos BC",
      ru: "Панатинайкос",
      de: "Panathinaikos Athen",
      es: "Panathinaikos",
      fr: "Panathinaïkos",
      zh: "帕纳辛奈克斯",
      el: "Παναθηναϊκός",
      nl: "Panathinaikos",
      pt: "Panathinaikos",
      it: "Panathinaikos",
    },
    name_short: "Panathinaikos",
    name_full: "Panathinaikos BC",
    name_code: "PAN",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "GRC",
    country: "Greece",
    flag: "greece",
    foundation: null,
    details: null,
  },
  {
    id: 46,
    sport_id: 3,
    category_id: 273,
    venue_id: null,
    manager_id: null,
    slug: "sk-tirana",
    name: "KB Tirana",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/sk-tirana.png",
    name_translations: {
      en: "KB Tirana",
      ru: "Ск Тирана",
    },
    name_short: "Tirana",
    name_full: "KB Tirana",
    name_code: "TIR",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ALB",
    country: "Albania",
    flag: "albania",
    foundation: null,
    details: null,
  },
  {
    id: 47,
    sport_id: 3,
    category_id: 273,
    venue_id: 10714,
    manager_id: null,
    slug: "teuta",
    name: "KB Teuta",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/teuta.png",
    name_translations: {
      en: "KB Teuta",
      ru: "Теута",
    },
    name_short: "KB Teuta",
    name_full: "KB Teuta",
    name_code: "TEU",
    has_sub: false,
    gender: null,
    is_nationality: false,
    country_code: "ALB",
    country: "Albania",
    flag: "albania",
    foundation: null,
    details: null,
  },
  {
    id: 48,
    sport_id: 3,
    category_id: 157,
    venue_id: 7078,
    manager_id: null,
    slug: "boca-juniors",
    name: "Boca Juniors",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/boca-juniors.png",
    name_translations: {
      en: "Boca Juniors",
      ru: "Бока Хуниорс",
      de: "Boca Juniors",
      es: "Boca Juniors",
      zh: "博卡青年篮球俱乐部",
      el: "Μπόκα Τζούνιορς",
      nl: "Boca Juniors",
      pt: "Boca Juniors",
    },
    name_short: "Boca Jrs",
    name_full: "Boca Juniors",
    name_code: "BOC",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 49,
    sport_id: 3,
    category_id: 157,
    venue_id: 6973,
    manager_id: null,
    slug: "obras-sanitarias",
    name: "Obras Sanitarias",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/obras-sanitarias.png",
    name_translations: {
      en: "Obras Sanitarias",
      ru: "Обрас Санитариас",
      de: "Obras Sanitarias",
      es: "Obras Sanitarias",
      zh: "奥布拉斯",
      el: "Ομπρίας Σανιτάριας",
      nl: "Obras Sanitarias",
      pt: "Obras Sanitárias",
    },
    name_short: "Obras",
    name_full: "Obras Sanitarias",
    name_code: "OBR",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 50,
    sport_id: 3,
    category_id: 157,
    venue_id: 6094,
    manager_id: null,
    slug: "instituto-de-cordoba",
    name: "Instituto Atlético Central Córdoba",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/instituto-de-cordoba.png",
    name_translations: {
      en: "Instituto Atlético Central Córdoba",
      ru: "Институто Атлетико Кордоба",
      de: "IA Central Cordoba",
      zh: "科尔多瓦学院",
      el: "Ινστιτούτι Ετλέτικο Σέντραλ Κόρντομπα",
      it: "INSTITUTO ATLETICO CENTRAL CORDOBA",
      nl: "Instituto Atletico Central Cordoba",
      pt: "Instituto Atlético Central Cordoba",
      tr: "Instituto Atletico Central Cordoba",
    },
    name_short: "Instituto",
    name_full: "Instituto Atlético Central Córdoba",
    name_code: "ACC",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 51,
    sport_id: 3,
    category_id: 157,
    venue_id: 7079,
    manager_id: null,
    slug: "la-union-de-formosa",
    name: "La Unión de Formosa",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/la-union-de-formosa.png",
    name_translations: {
      en: "La Unión de Formosa",
      ru: "Ла Унион Формоса",
      de: "La Union Formosa",
      es: "La Unión Formosa",
      zh: "福尔摩莎篮球队",
      el: "Φορμόσα",
      nl: "La Union Formosa",
      pt: "União Formosa",
    },
    name_short: "La Unión",
    name_full: "La Unión de Formosa",
    name_code: "LUF",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 52,
    sport_id: 3,
    category_id: 157,
    venue_id: 6945,
    manager_id: null,
    slug: "ferro-carril-oeste",
    name: "Ferro Carril Oeste",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/ferro-carril-oeste.png",
    name_translations: {
      en: "Ferro Carril Oeste",
      ru: "Ферро Карриль Оэсте",
      de: "Ferro Carril Oeste",
      zh: "西部铁路俱乐部",
      el: "Φέρρο Κάρριλ Οέστε",
      it: "FERRO CARRIL OESTE",
      nl: "Ferro Carril Oeste",
      pt: "Ferro Carril Oeste",
    },
    name_short: "Ferro Carril Oeste",
    name_full: "Ferro Carril Oeste",
    name_code: "FCO",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 53,
    sport_id: 3,
    category_id: 157,
    venue_id: 6154,
    manager_id: null,
    slug: "penarol-mar-del-plata",
    name: "Peñarol Mar del Plata",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/penarol-mar-del-plata.png",
    name_translations: {
      en: "Peñarol Mar del Plata",
      ru: "Пеньяроль",
      de: "Penarol Mar Del Plata",
      es: "Peñarol Mar Del Plata",
      zh: "马德普拉塔帕纳洛尔",
      el: "Πενιαρόλ ντελ Λα Πλάτα",
      nl: "Penarol Mar Del Plata",
      pt: "Penarõl Mar Del Plata",
    },
    name_short: "Peñarol",
    name_full: "Peñarol Mar del Plata",
    name_code: "PEN",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 54,
    sport_id: 3,
    category_id: 157,
    venue_id: 7030,
    manager_id: null,
    slug: "san-lorenzo-de-almagro",
    name: "San Lorenzo de Almagro",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/san-lorenzo-de-almagro.png",
    name_translations: {
      en: "San Lorenzo de Almagro",
      ru: "Сан-Лоренсо де Альмагро",
      de: "CA San Lorenzo de Almagro",
      zh: "圣洛伦索竞技",
      el: "Κλαμπ Ετλέτικο Σαν Λορένζο Ντε Αλμάγκρο",
      it: "CLUB ATLETICO SAN LORENZO DE ALMAGRO",
      nl: "Club Atletico San Lorenzo De Almagro",
      pt: "CA San Lorenzo de Almagro",
      tr: "CA San Lorenzo De Almagro",
    },
    name_short: "San Lorenzo",
    name_full: "San Lorenzo de Almagro",
    name_code: "SLA",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 55,
    sport_id: 3,
    category_id: 157,
    venue_id: null,
    manager_id: null,
    slug: "weber-bahia-basket",
    name: "Weber Bahía Basket",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/weber-bahia-basket.png",
    name_translations: {
      en: "Weber Bahía Basket",
      ru: "Вебер Баия Баскет",
      zh: "巴伊亚篮球",
      pt: "Bahia Basquetebol",
    },
    name_short: "Weber Bahía",
    name_full: "Weber Bahía Basket",
    name_code: "WBB",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 56,
    sport_id: 3,
    category_id: 157,
    venue_id: 7102,
    manager_id: null,
    slug: "gimnasia-comodoro-rivadavia",
    name: "Gimnasia Comodoro Rivadavia",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/gimnasia-comodoro-rivadavia.png",
    name_translations: {
      en: "Gimnasia Comodoro Rivadavia",
      ru: "Химнаcия и Эсгрима",
      de: "Gimnasia Indalo",
      es: "Gimnasia Índalo",
      zh: "科摩多罗",
      el: "Ιντάλο",
      nl: "Gimnasia Indalo",
      pt: "Gimnasia Indalo",
      tr: "Gimnasia De Comodoro",
    },
    name_short: "Gimnasia CR",
    name_full: "Gimnasia Comodoro Rivadavia",
    name_code: "COM",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 57,
    sport_id: 3,
    category_id: 157,
    venue_id: null,
    manager_id: null,
    slug: "club-deportivo-libertad",
    name: "Club Deportivo Libertad",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/club-deportivo-libertad.png",
    name_translations: {
      en: "Club Deportivo Libertad",
      ru: "Клуб Депортиво Либертад",
      zh: "利伯泰迪俱乐部",
      pt: "CD Libertad",
      de: "CD Libertad",
    },
    name_short: "Libertad",
    name_full: "Club Deportivo Libertad",
    name_code: "CDL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 58,
    sport_id: 3,
    category_id: 157,
    venue_id: 6816,
    manager_id: null,
    slug: "regatas-corrientes",
    name: "Regatas Corrientes",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/regatas-corrientes.png",
    name_translations: {
      en: "Regatas Corrientes",
      ru: "Регатас Корриетес",
      de: "Regatas Corrientes",
      es: "Regatas Corriente",
      zh: "科连特斯",
      el: "Κοριέντες",
      nl: "Regatas Corrientes",
      pt: "Regatas Corrientes",
    },
    name_short: "Regatas",
    name_full: "Regatas Corrientes",
    name_code: "REG",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 59,
    sport_id: 3,
    category_id: 157,
    venue_id: 6111,
    manager_id: null,
    slug: "quimsa-santiago-del-estero",
    name: "Quimsa Santiago del Estero",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/quimsa-santiago-del-estero.png",
    name_translations: {
      en: "Quimsa Santiago del Estero",
      ru: "Куимса Сантьяго-дель-Эстеро",
      de: "Quimsa Santiogo",
      es: "Quimsa Santiago Del Estero",
      zh: "圣地亚哥奎姆萨",
      el: "Κίμσα Σαντιόγκο",
      nl: "Quimsa Santiogo Del Estero",
      pt: "Quimsa Santiago Del Estero",
      tr: "Quimsa Santiago Del Estero",
    },
    name_short: "Quimsa",
    name_full: "Quimsa Santiago del Estero",
    name_code: "QSE",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 60,
    sport_id: 3,
    category_id: 157,
    venue_id: null,
    manager_id: null,
    slug: "san-lorenzo-de-almagro-1",
    name: "San Lorenzo de Almagro U23",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/san-lorenzo-de-almagro-1.png",
    name_translations: {
      en: "San Lorenzo de Almagro U23",
      ru: "Сан-Лоренсо Де Альмагро",
    },
    name_short: "San Lorenzo de Almagro",
    name_full: "San Lorenzo de Almagro U23",
    name_code: "SLD",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 61,
    sport_id: 3,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "weber-bahia",
    name: "Weber Bahía",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/weber-bahia.png",
    name_translations: {
      en: "Weber Bahía",
      ru: "Вебер Баия",
    },
    name_short: "Weber Bahía",
    name_full: "Weber Bahía",
    name_code: "WBA",
    has_sub: false,
    gender: null,
    is_nationality: false,
    country_code: null,
    country: null,
    flag: null,
    foundation: null,
    details: null,
  },
  {
    id: 62,
    sport_id: 3,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "club-presidente-derqui",
    name: "Club Presidente Derqui",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/club-presidente-derqui.png",
    name_translations: {
      en: "Club Presidente Derqui",
      ru: "Клуб Presidente Derqui",
    },
    name_short: "Derqui",
    name_full: "Club Presidente Derqui",
    name_code: "CPD",
    has_sub: false,
    gender: null,
    is_nationality: false,
    country_code: null,
    country: null,
    flag: null,
    foundation: null,
    details: null,
  },
  {
    id: 63,
    sport_id: 3,
    category_id: null,
    venue_id: null,
    manager_id: null,
    slug: "somisa-de-san-nicolas",
    name: "Somisa de San Nicolás",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/somisa-de-san-nicolas.png",
    name_translations: {
      en: "Somisa de San Nicolás",
      ru: "Сомиса Де Сан Николас",
    },
    name_short: "Somisa de San Nicolás",
    name_full: "Somisa de San Nicolás",
    name_code: "SDS",
    has_sub: false,
    gender: null,
    is_nationality: false,
    country_code: null,
    country: null,
    flag: null,
    foundation: null,
    details: null,
  },
  {
    id: 64,
    sport_id: 3,
    category_id: 157,
    venue_id: null,
    manager_id: null,
    slug: "estudiantes-de-la-plata",
    name: "Estudiantes de La Plata",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/estudiantes-de-la-plata.png",
    name_translations: {
      en: "Estudiantes de La Plata",
      ru: "Эстудиантес Де Ла Плата",
    },
    name_short: "Estudiantes de La Plata",
    name_full: "Estudiantes de La Plata",
    name_code: "EDL",
    has_sub: false,
    gender: null,
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 65,
    sport_id: 3,
    category_id: 157,
    venue_id: null,
    manager_id: null,
    slug: "atletico-pilar",
    name: "Atlético Pilar",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/atletico-pilar.png",
    name_translations: {
      en: "Atlético Pilar",
      ru: "Атлетико Пилар",
    },
    name_short: "Atlético Pilar",
    name_full: "Atlético Pilar",
    name_code: "CAP",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ARG",
    country: "Argentina",
    flag: "argentina",
    foundation: null,
    details: null,
  },
  {
    id: 66,
    sport_id: 4,
    category_id: 199,
    venue_id: 27,
    manager_id: 10106,
    slug: "boston-bruins",
    name: "Boston Bruins",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/boston-bruins.png",
    name_translations: {
      en: "Boston Bruins",
      ru: "Бостон Браинс",
      de: "Boston Bruins",
      es: "Boston Bruins",
      fr: "Boston Bruins",
      zh: "波士顿棕熊",
      el: "Μπόστον Μπρούινς",
      nl: "Boston Bruins",
      pt: "Boston Bruins",
    },
    name_short: "Bruins",
    name_full: "Boston Bruins",
    name_code: "BOS",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 67,
    sport_id: 4,
    category_id: 199,
    venue_id: 28,
    manager_id: 11332,
    slug: "detroit-red-wings",
    name: "Detroit Red Wings",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/detroit-red-wings.png",
    name_translations: {
      en: "Detroit Red Wings",
      ru: "Детройт Ред Вингс",
      de: "Detroit Red Wings",
      es: "Detroit Red Wings",
      fr: "Détroit Red Wings",
      zh: "底特律红翼",
      el: "Ντιτρόιτ Ρεντ Γουίνγκς",
      nl: "Detroit Red Wings",
      pt: "Detroit Red Wings",
    },
    name_short: "Red Wings",
    name_full: "Detroit Red Wings",
    name_code: "DET",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 68,
    sport_id: 4,
    category_id: 199,
    venue_id: 29,
    manager_id: 27,
    slug: "st-louis-blues",
    name: "St. Louis Blues",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/st-louis-blues.png",
    name_translations: {
      en: "St. Louis Blues",
      ru: "Сейнт-Льюис Блюз",
      de: "St. Louis Blues",
      es: "St. Louis Blues",
      fr: "St. Louis Blues",
      zh: "圣路易蓝调",
      el: "Σεντ Λούις Μπλουζ",
      nl: "St. Louis Blues",
      pt: "St. Louis Blues",
    },
    name_short: "Blues",
    name_full: "St. Louis Blues",
    name_code: "STL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 69,
    sport_id: 4,
    category_id: 199,
    venue_id: 30,
    manager_id: 8235,
    slug: "nashville-predators",
    name: "Nashville Predators",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/nashville-predators.png",
    name_translations: {
      en: "Nashville Predators",
      ru: "Нэшвилл Предэйторс",
      de: "Nashville Predators",
      es: "Nashville Predators",
      fr: "Nashville Predators",
      zh: "纳什维尔掠夺者",
      el: "Νάσβιλ Πρεντίτορς",
      nl: "Nashville Predators",
      pt: "Nashville Predators",
    },
    name_short: "Predators",
    name_full: "Nashville Predators",
    name_code: "NSH",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 70,
    sport_id: 4,
    category_id: 199,
    venue_id: 31,
    manager_id: 77,
    slug: "florida-panthers",
    name: "Florida Panthers",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/florida-panthers.png",
    name_translations: {
      en: "Florida Panthers",
      ru: "Флорида Пантерс",
      de: "Florida Panthers",
      es: "Florida Panthers",
      fr: "Florida Panthers",
      zh: "佛罗里达美洲豹",
      el: "Φλόριντα Πάνθερς",
      nl: "Florida Panthers",
      pt: "Florida Panthers",
    },
    name_short: "Panthers",
    name_full: "Florida Panthers",
    name_code: "FLA",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 71,
    sport_id: 4,
    category_id: 208,
    venue_id: 32,
    manager_id: 11333,
    slug: "edmonton-oilers",
    name: "Edmonton Oilers",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/edmonton-oilers.png",
    name_translations: {
      en: "Edmonton Oilers",
      ru: "Эдмонтон Ойлерс",
      de: "Edmonton Oilers",
      es: "Edmonton Oilers",
      fr: "Edmonton Oilers",
      zh: "爱民顿油人",
      el: "Έντμοντον  Όιλερς",
      nl: "Edmonton Oilers",
      pt: "Edmonton Oilers",
    },
    name_short: "Oilers",
    name_full: "Edmonton Oilers",
    name_code: "EDM",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "CAN",
    country: "Canada",
    flag: "canada",
    foundation: null,
    details: null,
  },
  {
    id: 72,
    sport_id: 4,
    category_id: 199,
    venue_id: 33,
    manager_id: 29,
    slug: "tampa-bay-lightning",
    name: "Tampa Bay Lightning",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/tampa-bay-lightning.png",
    name_translations: {
      en: "Tampa Bay Lightning",
      ru: "Тампа Бэй",
      de: "Tampa Bay Lightning",
      es: "Tampa Bay Lightning",
      fr: "Tampa Bay Lightning",
      zh: "坦帕湾闪电",
      el: "Τάμπα Μπέι Λάιτνινγκ",
      nl: "Tampa Bay Lightning",
      pt: "Tampa Bay Lightning",
    },
    name_short: "Lightning",
    name_full: "Tampa Bay Lightning",
    name_code: "TB",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 73,
    sport_id: 4,
    category_id: 199,
    venue_id: 34,
    manager_id: 76,
    slug: "philadelphia-flyers",
    name: "Philadelphia Flyers",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/philadelphia-flyers.png",
    name_translations: {
      en: "Philadelphia Flyers",
      ru: "Филадельфия Флайерс",
      de: "Philadelphia Flyers",
      es: "Philadelphia Flyers",
      fr: "Philadelphia Flyers",
      zh: "费城飞人",
      el: "Φιλαδέλφεια Φλάιερς",
      nl: "Philadelphia Flyers",
      pt: "Philadelphia Flyers",
    },
    name_short: "Flyers",
    name_full: "Philadelphia Flyers",
    name_code: "PHI",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 74,
    sport_id: 4,
    category_id: 199,
    venue_id: 35,
    manager_id: 6898,
    slug: "minnesota-wild",
    name: "Minnesota Wild",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/minnesota-wild.png",
    name_translations: {
      en: "Minnesota Wild",
      ru: "Миннесота Вилд",
      de: "Minnesota Wild",
      es: "Minnesota Wild",
      fr: "Minnesota Wild",
      zh: "明尼苏达野人",
      el: "Μιννεσότα Γουάιλντ",
      nl: "Minnesota Wild",
      pt: "Minnesota Wild",
    },
    name_short: "Wild",
    name_full: "Minnesota Wild",
    name_code: "MIN",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 75,
    sport_id: 4,
    category_id: 199,
    venue_id: 36,
    manager_id: 71,
    slug: "san-jose-sharks",
    name: "San Jose Sharks",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/san-jose-sharks.png",
    name_translations: {
      en: "San Jose Sharks",
      ru: "Сан-Хосе Шаркс",
      de: "San Jose Sharks",
      es: "San Jose Sharks",
      fr: "San José Sharks",
      zh: "圣荷西鲨鱼",
      el: "Σαν Χοσέ Σαρξ",
      nl: "San Jose Sharks",
      pt: "San Jose Sharks",
    },
    name_short: "Sharks",
    name_full: "San Jose Sharks",
    name_code: "SJ",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 76,
    sport_id: 4,
    category_id: 208,
    venue_id: 37,
    manager_id: 11334,
    slug: "montreal-canadiens",
    name: "Montréal Canadiens",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/montreal-canadiens.png",
    name_translations: {
      en: "Montréal Canadiens",
      ru: "Монреаль Канадиенс",
      de: "Montreal Canadiens",
      es: "Montreal Canadiens",
      fr: "Montréal Canadiens",
      zh: "蒙特利尔加拿大人",
      el: "Μόντρεαλ Κανάντιενς",
      nl: "Montreal Canadiens",
      pt: "Montreal Canadiens",
    },
    name_short: "Canadiens",
    name_full: "Montréal Canadiens",
    name_code: "MTL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "CAN",
    country: "Canada",
    flag: "canada",
    foundation: null,
    details: null,
  },
  {
    id: 77,
    sport_id: 4,
    category_id: 199,
    venue_id: 38,
    manager_id: 32,
    slug: "dallas-stars",
    name: "Dallas Stars",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/dallas-stars.png",
    name_translations: {
      en: "Dallas Stars",
      ru: "Даллас Старз",
      de: "Dallas Stars",
      es: "Dallas Stars",
      fr: "Dallas Stars",
      zh: "达拉斯星",
      el: "Ντάλας Σταρς",
      nl: "Dallas Stars",
      pt: "Dallas Stars",
    },
    name_short: "Stars",
    name_full: "Dallas Stars",
    name_code: "DAL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 78,
    sport_id: 4,
    category_id: 208,
    venue_id: 39,
    manager_id: 11335,
    slug: "ottawa-senators",
    name: "Ottawa Senators",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/ottawa-senators.png",
    name_translations: {
      en: "Ottawa Senators",
      ru: "Оттава Синэйтерс",
      de: "Ottawa Senators",
      es: "Ottawa Senators",
      fr: "Ottawa Senators",
      zh: "渥太华参议员",
      el: "Οτάβα Σενάτορς",
      nl: "Ottawa Senators",
      pt: "Ottawa Senators",
    },
    name_short: "Senators",
    name_full: "Ottawa Senators",
    name_code: "OTT",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "CAN",
    country: "Canada",
    flag: "canada",
    foundation: null,
    details: null,
  },
  {
    id: 79,
    sport_id: 4,
    category_id: 208,
    venue_id: 40,
    manager_id: 34,
    slug: "toronto-maple-leafs",
    name: "Toronto Maple Leafs",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/toronto-maple-leafs.png",
    name_translations: {
      en: "Toronto Maple Leafs",
      ru: "ХК Торонто Мапл Лифс",
      de: "Toronto Maple Leafs",
      es: "Toronto Maple Leafs",
      fr: "Toronto Maple Leafs",
      zh: "多伦多枫叶",
      el: "Τορόντο Μέιπλ Λιφς",
      nl: "Toronto Maple Leafs",
      pt: "Toronto Mapel Leafs",
    },
    name_short: "Maple Leafs",
    name_full: "Toronto Maple Leafs",
    name_code: "TOR",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "CAN",
    country: "Canada",
    flag: "canada",
    foundation: null,
    details: null,
  },
  {
    id: 80,
    sport_id: 4,
    category_id: 199,
    venue_id: 41,
    manager_id: 35,
    slug: "colorado-avalanche",
    name: "Colorado Avalanche",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/colorado-avalanche.png",
    name_translations: {
      en: "Colorado Avalanche",
      ru: "Колорадо Эвэленч",
      de: "Colorado Avalanche",
      es: "Colorado Avalanche",
      fr: "Colorado Avalanche",
      zh: "科罗拉多雪崩",
      el: "Κολοράντο Αβαλάνς",
      nl: "Colorado Avalanche",
      pt: "Colorado Avalanche",
    },
    name_short: "Avalanche",
    name_full: "Colorado Avalanche",
    name_code: "COL",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 81,
    sport_id: 4,
    category_id: 199,
    venue_id: 42,
    manager_id: 11336,
    slug: "los-angeles-kings",
    name: "Los Angeles Kings",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/los-angeles-kings.png",
    name_translations: {
      en: "Los Angeles Kings",
      ru: "Лос-Анджелес Кингс",
      de: "Los Angeles Kings",
      es: "Los Angeles Kings",
      fr: "Los Angeles Kings",
      zh: "洛杉矶国王",
      el: "Λος Άντζελες Κινγκς",
      nl: "Los Angeles Kings",
      pt: "Los Angeles Kings",
    },
    name_short: "Kings",
    name_full: "Los Angeles Kings",
    name_code: "LA",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 82,
    sport_id: 4,
    category_id: 199,
    venue_id: 17842,
    manager_id: 11337,
    slug: "arizona-coyotes",
    name: "Arizona Coyotes",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/arizona-coyotes.png",
    name_translations: {
      en: "Arizona Coyotes",
      ru: "Аризона Койотис",
      de: "Arizona Coyotes",
      es: "Arizona Coyotes",
      fr: "Arizona Coyotes",
      zh: "亚利桑那州土狼",
      el: "Αριζόνα",
      nl: "Arizona Coyotes",
      pt: "Arizona Coyotes",
    },
    name_short: "Coyotes",
    name_full: "Arizona Coyotes",
    name_code: "ARI",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 83,
    sport_id: 4,
    category_id: 199,
    venue_id: 44,
    manager_id: 37,
    slug: "washington-capitals",
    name: "Washington Capitals",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/washington-capitals.png",
    name_translations: {
      en: "Washington Capitals",
      ru: "Вашингтон Кэпитэлз",
      de: "Washington Capitals",
      es: "Washington Capitals",
      fr: "Washington Capitals",
      zh: "华盛顿首都",
      el: "Ουάσινγκτον Κάπιταλς",
      nl: "Washington Capitals",
      pt: "Washington Capitals",
    },
    name_short: "Capitals",
    name_full: "Washington Capitals",
    name_code: "WSH",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 84,
    sport_id: 4,
    category_id: 208,
    venue_id: 45,
    manager_id: 6627,
    slug: "calgary-flames",
    name: "Calgary Flames",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/calgary-flames.png",
    name_translations: {
      en: "Calgary Flames",
      ru: "Калгари Флэймс",
      de: "Calgary Flames",
      es: "Calgary Flames",
      fr: "Calgary Flames",
      zh: "卡尔加里火焰",
      el: "Κάλγκαρι Φλέιμς",
      nl: "Calgary Flames",
      pt: "Calgary Flames",
    },
    name_short: "Flames",
    name_full: "Calgary Flames",
    name_code: "CGY",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "CAN",
    country: "Canada",
    flag: "canada",
    foundation: null,
    details: null,
  },
  {
    id: 85,
    sport_id: 4,
    category_id: 199,
    venue_id: 46,
    manager_id: 11207,
    slug: "chicago-blackhawks",
    name: "Chicago Blackhawks",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/chicago-blackhawks.png",
    name_translations: {
      en: "Chicago Blackhawks",
      ru: "Чикаго Блэкхокс",
      de: "Chicago Blackhawks",
      es: "Chicago Blackhawks",
      fr: "Chicago Blackhawks",
      zh: "芝加哥黑鹰",
      el: "Σικάγο Μπλάκχοξ",
      nl: "Chicago Blackhawks",
      pt: "Chicago Blackhawks",
    },
    name_short: "Blackhawks",
    name_full: "Chicago Blackhawks",
    name_code: "CHI",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 86,
    sport_id: 4,
    category_id: 199,
    venue_id: 4967,
    manager_id: 26,
    slug: "vegas-golden-knights",
    name: "Vegas Golden Knights",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/vegas-golden-knights.png",
    name_translations: {
      en: "Vegas Golden Knights",
      ru: "Вегас Голден Найтс",
      de: "Vegas Golden Knights",
      es: "Vegas Golden Knights",
      fr: "Vegas Golden Knights",
      zh: "维加斯黄金骑士",
      pt: "Vegas Golden Knights",
      el: "Βέγκας Γκόλντεν",
    },
    name_short: "Golden Knights",
    name_full: "Vegas Golden Knights",
    name_code: "VGK",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 87,
    sport_id: 4,
    category_id: 199,
    venue_id: 14523,
    manager_id: 11338,
    slug: "new-york-islanders",
    name: "New York Islanders",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/new-york-islanders.png",
    name_translations: {
      en: "New York Islanders",
      ru: "Нью-Йорк Айлендерс",
      de: "New York Islanders",
      es: "New York Islanders",
      fr: "New York Islanders",
      zh: "纽约岛人",
      el: "Νιου Γιορκ Άιλαντερς",
      nl: "New York Islanders",
      pt: "New York Islanders",
    },
    name_short: "Islanders",
    name_full: "New York Islanders",
    name_code: "NYI",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 88,
    sport_id: 4,
    category_id: 199,
    venue_id: 49,
    manager_id: 41,
    slug: "pittsburgh-penguins",
    name: "Pittsburgh Penguins",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/pittsburgh-penguins.png",
    name_translations: {
      en: "Pittsburgh Penguins",
      ru: "Питтсбург Пингвинс",
      de: "Pittsburgh Penguins",
      es: "Pittsburgh Penguins",
      fr: "Pittsburgh Penguins",
      zh: "匹兹堡企鹅",
      el: "Πίτσμπουργκ Πένγκουινς",
      nl: "Pittsburgh Penguins",
      pt: "Pittsburgh Penguins",
    },
    name_short: "Penguins",
    name_full: "Pittsburgh Penguins",
    name_code: "PIT",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "USA",
    country: "USA",
    flag: "usa",
    foundation: null,
    details: null,
  },
  {
    id: 89,
    sport_id: 5,
    category_id: 240,
    venue_id: 50,
    manager_id: 8219,
    slug: "cucine-lube-civitanova",
    name: "Cucine Lube Civitanova",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/cucine-lube-civitanova.png",
    name_translations: {
      en: "Cucine Lube Civitanova",
      ru: "Cucine Любэ Чивитанова",
      de: "Volley Civitanova",
      fr: "Volley Civitanova",
      zh: "奇维塔诺瓦排球",
      el: "Σιβιτανόβα",
      it: "Civitanova",
      nl: "Volley Civitanova",
      pt: "Voleibol Civitanova",
      tr: "Volley Civitanova",
    },
    name_short: "Lube",
    name_full: "Cucine Lube Civitanova",
    name_code: "CIV",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 90,
    sport_id: 5,
    category_id: 240,
    venue_id: 15028,
    manager_id: null,
    slug: "tonno-callipo-vibo-valentia",
    name: "Tonno Calippo Calabria Vivo Valentia",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/tonno-callipo-vibo-valentia.png",
    name_translations: {
      en: "Tonno Calippo Calabria Vivo Valentia",
      ru: "Тонно Каллипо Вибо Валентия",
      de: "Volley Calabria Vibo Valentia",
      zh: "加里波排球队",
      el: "Βαλέντια",
      pt: "Voleibol Calabria Vibo Valentia",
      tr: "Volley Calabria Vibo Valentia",
    },
    name_short: "Vibo Valentia",
    name_full: "Tonno Calippo Calabria Vivo Valentia",
    name_code: "CVV",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 91,
    sport_id: 5,
    category_id: 240,
    venue_id: 52,
    manager_id: null,
    slug: "porto-robur-costa-ravenna",
    name: "Consar Ravenna",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/porto-robur-costa-ravenna.png",
    name_translations: {
      en: "Consar Ravenna",
      ru: "Равенна",
      de: "PRC Ravenna",
      es: "PRC Ravenna",
      zh: "PRC 拉文纳",
      el: "Ραβένα",
      it: "PRC Ravenna",
      nl: "PRC Ravenna",
      pt: "PRC Ravenna",
      tr: "PRC Ravenna",
    },
    name_short: "Ravenna",
    name_full: "Consar Ravenna",
    name_code: "RAV",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 92,
    sport_id: 5,
    category_id: 240,
    venue_id: 53,
    manager_id: 11006,
    slug: "sir-safety-perugia",
    name: "Sir Safety Perugia",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/sir-safety-perugia.png",
    name_translations: {
      en: "Sir Safety Perugia",
      ru: "Сэр Безопасности Перуджа",
      de: "Perugia Umbria Volley",
      fr: "Pérouse Umbria Volley",
      zh: "佩鲁贾翁布里亚排球",
      el: "Περούτζια",
      it: "Perugia",
      nl: "Perugia Umbria Volley",
      pt: "Perugia Umbria Voleibol",
      tr: "Perugia Umbria Volley",
    },
    name_short: "Perugia",
    name_full: "Sir Safety Perugia",
    name_code: "PUV",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 93,
    sport_id: 5,
    category_id: 240,
    venue_id: 7418,
    manager_id: 11001,
    slug: "power-volley-milano",
    name: "Allianz Milano",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/power-volley-milano.png",
    name_translations: {
      en: "Allianz Milano",
      ru: "Power Volley Milano",
      de: "Power Volley Milano",
      zh: "米兰力量排球",
      el: "Μιλάνο",
      pt: "Power Volley Milão",
    },
    name_short: "Milano",
    name_full: "Allianz Milano",
    name_code: "POM",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 94,
    sport_id: 5,
    category_id: 240,
    venue_id: null,
    manager_id: null,
    slug: "argos-volley-sora",
    name: "Argos Volley Sora",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/argos-volley-sora.png",
    name_translations: {
      en: "Argos Volley Sora",
      ru: "Аргос Волей Сора",
      de: "Argos Volley Sora",
      zh: "索拉阿戈斯排球",
      el: "Άργκος Σόρα",
      it: "Argos Sora",
      pt: "Argos Voleibol Sora",
    },
    name_short: "Argos",
    name_full: "Argos Volley Sora",
    name_code: "ARG",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 95,
    sport_id: 5,
    category_id: 240,
    venue_id: 15072,
    manager_id: 12476,
    slug: "taiwan-excellence-latina",
    name: "Cisterna Volley",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/taiwan-excellence-latina.png",
    name_translations: {
      en: "Cisterna Volley",
      ru: "Андреоли Латина",
      de: "TOP Volley Cisterna",
      es: "Andreoli Latina",
      zh: "拉蒂纳顶级排球",
      el: "Σιστέρνα",
      it: "Andreoli Latina",
      nl: "Andreoli Latina",
      pt: "Top Voleibol Cisterna",
      tr: "Top Volley Cisterna",
    },
    name_short: "Cisterna",
    name_full: "Cisterna Volley",
    name_code: "CIS",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 96,
    sport_id: 5,
    category_id: 240,
    venue_id: 56,
    manager_id: 11003,
    slug: "padova",
    name: "Pallavolo Padova",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/padova.png",
    name_translations: {
      en: "Pallavolo Padova",
      ru: "Падуя",
      de: "Pallavolo Padova",
      zh: "帕拉沃洛",
      el: "Πάντοβα",
      pt: "Pallavolo Padova",
      tr: "Pallavolo Padova",
    },
    name_short: "Padova",
    name_full: "Pallavolo Padova",
    name_code: "PAP",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 97,
    sport_id: 5,
    category_id: 240,
    venue_id: 9075,
    manager_id: 11004,
    slug: "vero-volley-team-monza",
    name: "Vero Volley Monza",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/vero-volley-team-monza.png",
    name_translations: {
      en: "Vero Volley Monza",
      ru: "Vero Volley Team Монца",
      de: "VV Monza",
      zh: "蒙扎维罗排球",
      el: "Μόντζα",
      pt: "VV Monza",
      tr: "VV Monza",
    },
    name_short: "Monza",
    name_full: "Vero Volley Monza",
    name_code: "VVM",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 98,
    sport_id: 5,
    category_id: 240,
    venue_id: 57,
    manager_id: 11005,
    slug: "calzedonia-verona",
    name: "Rana Verona",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/calzedonia-verona.png",
    name_translations: {
      en: "Rana Verona",
      ru: "Кальзедония Верона",
      de: "Volley Verona",
      zh: "维罗纳排球",
      el: "Βερόνα",
      nl: "Volley Verona",
      pt: "Volley Verona",
      tr: "Volley Verona",
    },
    name_short: "Verona",
    name_full: "Rana Verona",
    name_code: "VER",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 99,
    sport_id: 5,
    category_id: 240,
    venue_id: 58,
    manager_id: 11002,
    slug: "trentino-volley",
    name: "Itas Trentino",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/trentino-volley.png",
    name_translations: {
      en: "Itas Trentino",
      ru: "Трентино",
      de: "Trentino",
      es: "Trentino Volley",
      zh: "特伦蒂诺排球",
      el: "Τρεντίνο",
      it: "Trento",
      nl: "Trentino Volley",
      pt: "Diatec Trentino",
    },
    name_short: "Trentino",
    name_full: "Itas Trentino",
    name_code: "TRE",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
  {
    id: 100,
    sport_id: 5,
    category_id: 240,
    venue_id: 59,
    manager_id: 12477,
    slug: "modena-volley",
    name: "Valsa Group Modena",
    has_logo: true,
    logo: "https://tipsscore.com/resb/team/modena-volley.png",
    name_translations: {
      en: "Valsa Group Modena",
      ru: "Модена Волейбол",
      de: "Modena Volley",
      fr: "Modène Volley",
      zh: "摩德纳排球",
      el: "Μόντενα",
      nl: "Modena Volley",
      pt: "Modena Vólei",
      tr: "Modena Volley",
    },
    name_short: "Modena",
    name_full: "Valsa Group Modena",
    name_code: "MOD",
    has_sub: false,
    gender: "M",
    is_nationality: false,
    country_code: "ITA",
    country: "Italy",
    flag: "italy",
    foundation: null,
    details: null,
  },
];
